name: CI/CD pipeline
run-name: check tsc / lint / test and etc 🚀
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.16.0]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn -v
      # equals to `npm ci`
      - run: yarn install --frozen-lockfile
      - run: yarn tsc && yarn test
      - run: yarn build
  